In [1]:
import sys
sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

from src.data import get_data, split_data
from src.features import clean_data, prepare_data

In [2]:
df = get_data()
df.shape

(148670, 34)

In [3]:
df_train, df_val, df_test, df_full_train = split_data(df)

In [4]:
df_train.head()

,id,year,loan_limit,gender,approv_in_adv,loan_type,loan_purpose,credit_worthiness,open_credit,business_or_commercial,...,credit_type,credit_score,co-applicant_credit_type,age,submission_of_application,ltv,region,security_type,status,dtir1
0,114476,2019,cf,sex_not_available,nopre,type1,p3,l1,nopc,nob/c,...,exp,663,exp,65-74,to_inst,55.527211,south,direct,0,42.0
1,28663,2019,cf,male,nopre,type1,p3,l1,nopc,nob/c,...,cib,572,exp,45-54,to_inst,53.627968,north,direct,0,20.0
2,34413,2019,cf,sex_not_available,nopre,type1,p1,l1,nopc,nob/c,...,exp,808,exp,35-44,to_inst,59.965831,south,direct,0,38.0
3,65252,2019,cf,sex_not_available,nopre,type2,p3,l1,nopc,b/c,...,equi,607,exp,55-64,to_inst,NaN,south,direct,1,NaN
4,46636,2019,cf,joint,nopre,type1,p1,l1,nopc,nob/c,...,crif,678,exp,35-44,to_inst,93.639053,north,direct,1,41.0


In [5]:
df_train, medians = clean_data(df_train, fit=True)


In [6]:
df_train.head()

,loan_limit,gender,approv_in_adv,loan_type,loan_purpose,credit_worthiness,open_credit,business_or_commercial,loan_amount,term,...,co-applicant_credit_type,age,submission_of_application,ltv,region,security_type,status,dtir1,dtir1_was_missing,property_value_was_missing
0,cf,sex_not_available,nopre,type1,p3,l1,nopc,nob/c,326500,360.0,...,exp,65-74,to_inst,55.527211,south,direct,0,42.0,0,0
1,cf,male,nopre,type1,p3,l1,nopc,nob/c,406500,360.0,...,exp,45-54,to_inst,53.627968,north,direct,0,20.0,0,0
2,cf,sex_not_available,nopre,type1,p1,l1,nopc,nob/c,526500,180.0,...,exp,35-44,to_inst,59.965831,south,direct,0,38.0,0,0
3,cf,sex_not_available,nopre,type2,p3,l1,nopc,b/c,66500,360.0,...,exp,55-64,to_inst,75.122549,south,direct,1,39.0,1,1
4,cf,joint,nopre,type1,p1,l1,nopc,nob/c,316500,324.0,...,exp,35-44,to_inst,93.639053,north,direct,1,41.0,0,0


In [7]:
medians

{'income': np.float64(5760.0),
 'dtir1': np.float64(39.0),
 'property_value': np.float64(418000.0),
 'ltv': np.float64(75.12254902)}

In [8]:
df_val, medians = clean_data(df_val, fit=False, medians=medians)

In [9]:
df_val.head()

,loan_limit,gender,approv_in_adv,loan_type,loan_purpose,credit_worthiness,open_credit,business_or_commercial,loan_amount,term,...,co-applicant_credit_type,age,submission_of_application,ltv,region,security_type,status,dtir1,dtir1_was_missing,property_value_was_missing
0,ncf,male,pre,type3,p3,l1,nopc,nob/c,136500,360.0,...,exp,35-44,to_inst,75.122549,north,direct,1,39.0,1,1
1,cf,joint,nopre,type1,p4,l1,nopc,nob/c,306500,360.0,...,exp,35-44,not_inst,88.074713,north,direct,0,32.0,0,0
2,cf,sex_not_available,nopre,type1,p1,l1,nopc,nob/c,366500,360.0,...,exp,35-44,to_inst,75.122549,south,direct,1,39.0,1,1
3,cf,male,nopre,type1,p3,l1,nopc,nob/c,606500,360.0,...,cib,45-54,not_inst,78.971354,north,direct,0,31.0,0,0
4,cf,sex_not_available,nopre,type1,p4,l1,nopc,nob/c,106500,360.0,...,cib,>74,to_inst,9.879406,south,direct,0,40.0,0,0


In [10]:
medians

{'income': np.float64(5760.0),
 'dtir1': np.float64(39.0),
 'property_value': np.float64(418000.0),
 'ltv': np.float64(75.12254902)}

In [11]:
df_train.nunique().sort_values(ascending=False)

ltv                           6840
income                         846
credit_score                   401
property_value                 345
loan_amount                    192
dtir1                           57
term                            25
age                              7
region                           4
total_units                      4
gender                           4
credit_type                      4
loan_purpose                     4
loan_type                        3
occupancy_type                   3
submission_of_application        2
security_type                    2
status                           2
co-applicant_credit_type         2
dtir1_was_missing                2
loan_limit                       2
secured_by                       2
construction_type                2
lump_sum_payment                 2
interest_only                    2
neg_ammortization                2
business_or_commercial           2
open_credit                      2
credit_worthiness   

In [12]:
X_train, y_train, encoder, features = prepare_data(df_train, fit=True)


In [13]:
X_train, y_train

(array([[3.265e+05, 3.600e+02, 5.880e+05, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [4.065e+05, 3.600e+02, 7.580e+05, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [5.265e+05, 1.800e+02, 8.780e+05, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        ...,
        [4.265e+05, 3.600e+02, 5.680e+05, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [4.965e+05, 3.600e+02, 1.108e+06, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [3.565e+05, 3.600e+02, 4.480e+05, ..., 0.000e+00, 0.000e+00,
         0.000e+00]], shape=(86399, 47)),
 array([0, 0, 0, ..., 0, 0, 1], shape=(86399,)))

In [14]:
len(features), features

(47,
 ['loan_amount',
  'term',
  'property_value',
  'income',
  'credit_score',
  'ltv',
  'dtir1',
  'loan_limit_ncf',
  'gender_joint',
  'gender_male',
  'gender_sex_not_available',
  'approv_in_adv_pre',
  'loan_type_type2',
  'loan_type_type3',
  'loan_purpose_p2',
  'loan_purpose_p3',
  'loan_purpose_p4',
  'credit_worthiness_l2',
  'open_credit_opc',
  'business_or_commercial_nob/c',
  'neg_ammortization_not_neg',
  'interest_only_not_int',
  'lump_sum_payment_not_lpsm',
  'construction_type_sb',
  'occupancy_type_pr',
  'occupancy_type_sr',
  'secured_by_land',
  'total_units_2u',
  'total_units_3u',
  'total_units_4u',
  'credit_type_crif',
  'credit_type_equi',
  'credit_type_exp',
  'co-applicant_credit_type_exp',
  'age_35-44',
  'age_45-54',
  'age_55-64',
  'age_65-74',
  'age_<25',
  'age_>74',
  'submission_of_application_to_inst',
  'region_north',
  'region_north-east',
  'region_south',
  'security_type_indriect',
  'dtir1_was_missing_1',
  'property_value_was_miss

In [15]:
X_val, y_val, _, features_val = prepare_data(df_val, encoder=encoder)

In [16]:
X_val

array([[1.365e+05, 3.600e+02, 4.180e+05, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       [3.065e+05, 3.600e+02, 3.480e+05, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [3.665e+05, 3.600e+02, 4.180e+05, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       ...,
       [1.665e+05, 3.240e+02, 2.480e+05, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [3.765e+05, 3.600e+02, 5.480e+05, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [5.065e+05, 3.600e+02, 1.308e+06, ..., 0.000e+00, 0.000e+00,
        0.000e+00]], shape=(28747, 47))

# Training the model (base)

In [17]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

/Users/samisiraj/Desktop/Projects/loan-default-prediction/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is '

In [18]:
model.intercept_

array([-0.04986842])

In [19]:
model.coef_

array([[ 4.22841273e-07, -1.63577532e-03, -1.80215378e-07,
        -4.07238057e-05, -6.22327958e-04,  1.69455872e-04,
         1.06273978e-02,  1.12289288e-01, -2.22009856e-01,
         3.15402313e-02,  1.50333574e-01, -1.14956344e-01,
         1.57673008e-01, -3.42550008e-02,  3.84050718e-02,
         1.91427663e-04, -9.75103933e-02,  6.19221445e-02,
         4.24609553e-03, -2.07541385e-01, -3.54059438e-01,
        -8.89229861e-02, -2.77793573e-01, -5.27944694e-02,
        -1.41618615e-01,  2.02261122e-02,  2.92608949e-03,
         2.48516902e-02,  8.47014280e-03,  2.24344863e-03,
        -4.55166846e-01,  1.36347379e+00, -4.61643243e-01,
         5.93923835e-01, -9.18841279e-02, -1.71002397e-02,
         4.49372394e-02,  4.58511091e-02,  2.35213543e-03,
         4.87238334e-02,  3.32804990e-01, -2.23808118e-01,
         8.74593724e-03,  1.45365427e-01,  2.92608949e-03,
         1.19578826e+00,  1.36320403e+00]])

# Validating model using X_val

In [20]:
y_val_pred = model.predict_proba(X_val)[:,1]
y_val_pred

array([0.93240383, 0.09829026, 0.95077131, ..., 0.20831208, 0.09583095,
       0.18032634], shape=(28747,))

In [21]:
default_prediction = y_val_pred >= 0.35

In [22]:
y_val

array([1, 0, 1, ..., 0, 0, 1], shape=(28747,))

In [23]:
default_prediction.astype(int)

array([1, 0, 1, ..., 0, 0, 0], shape=(28747,))

In [24]:
(default_prediction == y_val).mean()

np.float64(0.8297561484676662)

In [25]:
default_prediction.mean()

np.float64(0.14989390197237973)

In [26]:
y_val.mean()

np.float64(0.2445124708665252)